---
title: "GO-enrichtment analysis"
description: |
  Overview of data analysis for the pilot samples.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(rtracklayer)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(ggpubr)
library(cowplot)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
source("helperFunctions.R")
```

```{r load-seurat}
fnames.seurat <- list.files(path = "data", ".*Seurat.*human.Rdata", full.names = T)
names.seurat <- lapply(fnames.seurat, load, .GlobalEnv)
seurat.full <- do.call(Map, c(f=list, sapply(names.seurat, as.symbol)))
seurat.full <- seurat.full[[1]]
names(seurat.full) <- names.seurat
```

```{r}
lapply(seurat.full, function(x){
    FetchData(x, "")
  }) %>% 
  bind_rows(.id = "idx") %>% 
  as_tibble(rownames = "cell_index") %>% 
  mutate(idx = str_remove_all(idx, "[^0-9]")) -> mt.data
```


```{r get-all-genes}
total.genes <- FetchData(seurat.full(list_seurat_1820h[["1820"]]@assays[["RNA"]]@data),
                    seurat.full(list_seurat_1822h[["1822"]]@assays[["RNA"]]@data),
                    seurat.full(list_seurat_7270h[["7270"]]@assays[["RNA"]]@data),
                    seurat.full(list_seurat_7271h[["7271"]]@assays[["RNA"]]@data),
                    seurat.full(list_seurat_7272h[["7272"]]@assays[["RNA"]]@data),
                    seurat.full(list_seurat_7273h[["7273"]]@assays[["RNA"]]@data))

mt.genes <- total.genes[grepl("^MT-", names(total.genes))]
head(mt.genes)
```

```{r}
hsmart <- useMart(dataset = "hsapiens_gene_ensembl", biomart = "ensembl")
total.genesid <- getBM(
  attributes = c("ensembl_gene_id", "hgnc_symbol"),
  values = total.genes,
  mart = hsmart)

total.genesid %>% arrange(ensembl_gene_id, hgnc_symbol)
```

```{r}
head(total.genesid)
```


```{r}
egohuman <- enrichGO(gene = total.genesid$ensembl_gene_id,
                 OrgDb = org.Hs.eg.db,
                 keyType = "ENSEMBL",
                 ont = "CC",
                 pAdjustMethod = "BH",
                 pvalueCutoff = 0.01,
                 qvalueCutoff = 0.05)
```

```{r}
gse <- gseGO(geneList = total.genesid$ensembl_gene_id,
             ont = "ALL",
             keyType = "ENSEMBL",
             nPerm = 10000,
             minGSSize = 3,
             maxGSSize = 800,
             pvalueCutoff = 0.05,
             verbose = TRUE,
             OrgDb = org.Hs.eg.db,
             pAdjustMethod = "none")
```

