---
title: "Integration"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(rtracklayer)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(ggpubr)
library(cowplot)
library(dplyr)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
library(SingleCellExperiment)
library(scales)
library(RCurl)
library(glmGamPoi)
source("helperFunctions.R")
```

```{r load-data}
split_seurat <- readRDS("data/split_seurat.rds")
#integrated_seurat <- readRDS("data/integrated_seurat.rds")
```

## Integration with Reciprocal PCA

```{r normalizatíon and variable feature selection}
split_seurat <- lapply(X = split_seurat, FUN = function(x){
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
}) 
```

```{r select features and run PCA}
features <- SelectIntegrationFeatures(object.list = split_seurat)
split_seurat <- lapply(X = split_seurat, FUN = function(x){
  x <- ScaleData(x, features = features, verbose = FALSE)
  x <- RunPCA(x, features = features, verbose = FALSE)
})
```

```{r}
options(future.globals.maxSize = 3 * 1024^3)
```

```{r Integrate across conditions}
immune.anchors <- FindIntegrationAnchors(object.list = split_seurat, anchor.features = features, reduction = "rpca", k.anchor = 20)
integrated_seurat <- IntegrateData(anchorset = immune.anchors)
```

```{r downstream analysis on the corrected data}
DefaultAssay(integrated_seurat) <- "integrated"
```

```{r workflow for visualization and clustering}
integrated_seurat <- ScaleData(integrated_seurat, verbose = FALSE)
integrated_seurat <- RunPCA(integrated_seurat, npcs = 30, verbose = FALSE)
integrated_seurat <- RunUMAP(integrated_seurat, reduction = "pca", dims = 1:30)
integrated_seurat <- FindNeighbors(integrated_seurat, reduction = "pca", dims = 1:30)
integrated_seurat <- FindClusters(integrated_seurat, resolution = 0.5)
```

```{r Visualization}
p1 <- DimPlot(integrated_seurat, reduction = "umap", group.by = "sample")
p2 <- DimPlot(integrated_seurat, reduction = "umap", label = TRUE, repel = TRUE)
p3 <- DimPlot(integrated_seurat, reduction = "umap", split.by = "sample")
p1
p2
p3
```

```{r}
PCAPlot(integrated_seurat, split.by = "sample")
```

```{r}
saveRDS(integrated_seurat, "data/integrated_seurat.rds")
```

