---
title: "Marker identification"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(rtracklayer)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(ggpubr)
library(cowplot)
library(dplyr)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
library(SingleCellExperiment)
library(scales)
library(RCurl)
library(metap)
source("helperFunctions.R")
```

```{r}
seurat_integrated_RNA <- readRDS("data/integrated_seurat_RNA.rds")
DefaultAssay(seurat_integrated_RNA) <- "RNA"
```

```{r}
cluster0_conserved_markers <- FindConservedMarkers(seurat_integrated_RNA,
                              ident.1 = 0,
                              grouping.var = "sample",
                              only.pos = TRUE,
		                          logfc.threshold = 0.25)
```

```{r}
# Adding gene annotations
annotations <- read.csv("data/annotation.csv")
```

```{r}
# Combine markers with gene descriptions 
cluster0_ann_markers <- cluster0_conserved_markers %>% 
                rownames_to_column(var="gene") %>% 
                left_join(y = unique(annotations[, c("gene_name", "description")]),
                          by = c("gene" = "gene_name"))

View(cluster0_ann_markers)
```

```{r}
# Create function to get conserved markers for any given cluster
get_conserved <- function(cluster){
  FindConservedMarkers(seurat_integrated_RNA,
                       ident.1 = cluster,
                       grouping.var = "sample",
                       only.pos = TRUE) %>%
    rownames_to_column(var = "gene") %>%
    left_join(y = unique(annotations[, c("gene_name", "description")]),
               by = c("gene" = "gene_name")) %>%
    cbind(cluster_id = cluster, .)
  }
```

```{r}
# Iterate function across desired clusters
conserved_markers <- map_dfr(c(0:16), get_conserved)
```

# Evaluating marker genes

```{r}
# Extract top 10 markers per cluster
top10 <- conserved_markers %>% 
  mutate(avg_fc = (`7272_avg_log2FC` + `7271_avg_log2FC` + `7270_avg_log2FC` + `7273_avg_log2FC` + `1822_avg_log2FC` + `1820_avg_log2FC`) /2) %>% 
  group_by(cluster_id) %>% 
  top_n(n = 10, 
        wt = avg_fc)

# Visualize top 10 markers per cluster
View(top10)

datatable(top10,
             caption = "The table shows the top 10 markers per cluster")
```

```{r}
write_rds(seurat_integrated_RNA,
          file = "data/seurat_Marker.rds")
```

