---
title: "Normalization and regressing out unwanted variation"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(rtracklayer)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(ggpubr)
library(cowplot)
library(dplyr)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
library(SingleCellExperiment)
library(scales)
library(RCurl)
source("helperFunctions.R")
```

```{r load data}
load("data/seuratmerged_filtered_tags.RData")
metadata <- filtered_seurat@meta.data
```

```{r normalize-counts}
seurat_phase <- NormalizeData(filtered_seurat)
```

```{r load-cell-cycle-markers}
load("data/cycle.rda")
```

```{r Score cells for cell cycle}
seurat_phase <- CellCycleScoring(seurat_phase, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)
```

```{r Identify the most variable genes}
seurat_phase <- FindVariableFeatures(seurat_phase,
                                     selection.method = "vst",
                                     nfeatures = 2000,
                                     verbose = FALSE)
```

```{r scale the counts}
seurat_phase <- ScaleData(seurat_phase)
```

```{r Perform PCA}
seurat_phase <- RunPCA(seurat_phase)
```

```{r}
seurat_phase_umap <- RunUMAP(seurat_phase,
                             dims = 1:40,
                             reduction = "pca")

```


```{r}
# Plot UMAP                             
DimPlot(seurat_phase_umap,
        reduction = "umap",
        split.by = "Sample_Tag",
        group.by = "Phase")   
```


```{r Plot the PCA colored by cell cycle phase}
DimPlot(seurat_phase,
        reduction = "pca",
        group.by= "Phase",
        split.by = "Phase")
```

```{r}
view(seurat_phase@meta.data)
```

```{r split seurat object by condition to perform cell cycle scoring and SCT on all samples}
split_seurat <- SplitObject(seurat_phase, split.by = "Sample_Tag")
```

```{r}
split_seurat <- split_seurat[c("1820", "1822", "7270", "7271", "7272", "7273")]
```

```{r}
options(future.globals.maxSize = 3 * 1024^3)
```

```{r}
for (i in 1:length(split_seurat)) {
    split_seurat[[i]] <- SCTransform(split_seurat[[i]], vars.to.regress = c("percent.mt"))
    }
```

```{r}
saveRDS(split_seurat, file="data/split_seurat.rds")
```
