---
title: "Normalization and regressing out unwanted variation"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
```

```{r}
options(future.globals.maxSize = 3 * 1024^3)
```

```{r load data}
load("data/filtered_unfiltered_Seurat.RData")
filtered_unfiltered_meta <- filtered_unfiltered_seurat@meta.data
```

```{r normalize-counts}
unfiltered_phase_seurat <- NormalizeData(filtered_unfiltered_seurat)
```

```{r load-cell-cycle-markers}
load("data/cycle.rda")
```

```{r Score cells for cell cycle}
unfiltered_phase_seurat <- CellCycleScoring(unfiltered_phase_seurat, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)
```

```{r Identify the most variable genes}
unfiltered_phase_seurat <- FindVariableFeatures(unfiltered_phase_seurat,
                                     selection.method = "vst",
                                     nfeatures = 2000,
                                     verbose = FALSE)
```

```{r scale the counts}
unfiltered_phase_seurat <- ScaleData(unfiltered_phase_seurat)
```

```{r Perform PCA}
unfiltered_phase_seurat <- RunPCA(unfiltered_phase_seurat)
```

```{r}
unfiltered_phase_umap_seurat <- RunUMAP(unfiltered_phase_seurat,
                                        dims = 1:40,
                                        reduction = "pca")

```

```{r}
# Plot UMAP                             
DimPlot(unfiltered_phase_umap_seurat,
        reduction = "umap",
        group.by = "Sample_Tag",
        split.by = "Phase")   
```


```{r Plot the PCA colored by cell cycle phase}
DimPlot(unfiltered_phase_seurat,
        reduction = "pca",
        group.by= "Phase",
        split.by = "Phase")
```

```{r}
view(unfiltered_phase_seurat@meta.data)
```

```{r split seurat object by condition to perform cell cycle scoring and SCT on all samples}
split_unfiltered_seurat <- SplitObject(unfiltered_phase_seurat, split.by = "seq_folder")
```

```{r}
split_unfiltered_seurat <- split_unfiltered_seurat[c("1820", "1822", "7270", "7271", "7272", "7273")]
```

```{r}
saveRDS(split_unfiltered_seurat, file="data/split_unfiltered_seurat.rds")
```



```{r}
split_unfiltered_sct_mt_seurat <- split_unfiltered_seurat 
  #load("data/split_unfiltered_seurat.rds")
```

```{r}
for (i in 1:length(split_unfiltered_sct_mt_seurat)) {
    split_unfiltered_sct_mt_seurat[[i]] <- SCTransform(split_unfiltered_sct_mt_seurat[[i]], vars.to.regress = c("percent.mt"))
    }
```

```{r}
saveRDS(split_unfiltered_sct_mt_seurat, file="data/split_unfiltered_sct_mt_seurat.rds")
```



```{r}
split_unfiltered_sct_phase_seurat <- split_unfiltered_seurat 
  #load("data/split_unfiltered_seurat.rds")
```

```{r}
for (i in 1:length(split_unfiltered_sct_phase_seurat)) {
    split_unfiltered_sct_phase_seurat[[i]] <- SCTransform(split_unfiltered_sct_phase_seurat[[i]], vars.to.regress = c("S.Score", "G2M.Score"))
    }
```

```{r}
saveRDS(split_unfiltered_sct_phase_seurat, file="data/split_unfiltered_sct_phase_seurat.rds")
```




```{r}
split_unfiltered_sct_mt_phase_seurat <- split_unfiltered_seurat
  #load("data/split_unfiltered_seurat.rds")
```

```{r}
for (i in 1:length(split_unfiltered_sct_mt_phase_seurat)) {
    split_unfiltered_sct_mt_phase_seurat[[i]] <- SCTransform(split_unfiltered_sct_mt_phase_seurat[[i]], vars.to.regress = c("S.Score", "G2M.Score"))
    }
```

```{r}
saveRDS(split_unfiltered_sct_mt_phase_seurat, file="data/split_unfiltered_sct_mt_phase_seurat.rds")
```