---
title: "Preparing data and qualtiy control"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(rtracklayer)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(ggpubr)
library(cowplot)
library(dplyr)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
library(SingleCellExperiment)
library(scales)
library(RCurl)
source("helperFunctions.R")
```

```{r load-seurat-object}
load("data/merged_seurat.RData")
```

```{r create-metadata-df}
metadata_merged <- merged_seurat@meta.data
```

```{r subset metadata for QC plots}
subset_pilots <- subset(metadata_merged, metadata_merged$seq_folder == "1820" | metadata_merged$seq_folder == "1822")
subset_7270 <- subset(metadata_merged, metadata_merged$seq_folder == 7270)
subset_7271 <- subset(metadata_merged, metadata_merged$seq_folder == 7271)
subset_7272 <- subset(metadata_merged, metadata_merged$seq_folder == 7272)
subset_7273 <- subset(metadata_merged, metadata_merged$seq_folder == 7273)
subset_control <- subset(metadata_merged, metadata_merged$Sample_Tag == "Control")
subset_alpelisib <- subset(metadata_merged, metadata_merged$Sample_Tag == "Alpelisib")
subset_copanlisib <- subset(metadata_merged, metadata_merged$Sample_Tag == "Copanlisib")
```

```{r visualize-pilot-samples-qcmetrices, fig.cap="The figures show various QC metrices from the pilot samples (1820 & 1822) and their sample tags."}
subset_pilots %>% 
  	ggplot(aes(x=Sample_Tag, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

subset_pilots %>% 
  	ggplot(aes(color=Sample_Tag, x=nUMI, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

subset_pilots %>% 
  	ggplot(aes(color=Sample_Tag, x=nGene, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

# subset_pilots %>%
#   	ggplot(aes(x=nGene, y=nUMI, color=Sample_Tag)) +
#   	geom_point() +
# 	scale_colour_gradient(low = "gray90", high = "black") +
#   	stat_smooth(method=lm) +
#   	scale_x_log10() +
#   	scale_y_log10() +
#   	theme_classic() +
#   	geom_vline(xintercept = 500) +
#   	geom_hline(yintercept = 250) +
#   	facet_wrap(~Sample_Tag)

subset_pilots %>% 
  	ggplot(aes(color=Sample_Tag, x=percent.mt, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)

```

```{r Visualize-qc-metrices-from-7270, fig.cap="The figures show the various QC metrices for sample 7270 and the corresponding samples tags."}

subset_7270 %>% 
  	ggplot(aes(x=Sample_Tag, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

subset_7270 %>% 
  	ggplot(aes(color=Sample_Tag, x=nUMI, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

subset_7270 %>% 
  	ggplot(aes(color=Sample_Tag, x=nGene, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

# subset_7270 %>% 
#   	ggplot(aes(x=nUMI, y=nGene, color=Sample_Tag)) + 
#   	geom_point() + 
# 	scale_colour_gradient(low = "gray90", high = "black") +
#   	stat_smooth(method=lm) +
#   	scale_x_log10() + 
#   	scale_y_log10() + 
#   	theme_classic() +
#   	geom_vline(xintercept = 500) +
#   	geom_hline(yintercept = 250) +
#   	facet_wrap(~Sample_Tag)

subset_7270 %>% 
  	ggplot(aes(color=Sample_Tag, x=percent.mt, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)
```

```{r Visualize-qc-metrices-for-sample-7271, fig.cap="The figures show various Qc metrices for sample 7271."}

subset_7271 %>% 
  	ggplot(aes(x=Sample_Tag, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

subset_7271 %>% 
  	ggplot(aes(color=Sample_Tag, x=nUMI, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

subset_7271 %>% 
  	ggplot(aes(color=Sample_Tag, x=nGene, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

# subset_7271 %>% 
#   	ggplot(aes(x=nUMI, y=nGene, color=Sample_Tag)) + 
#   	geom_point() + 
# 	scale_colour_gradient(low = "gray90", high = "black") +
#   	stat_smooth(method=lm) +
#   	scale_x_log10() + 
#   	scale_y_log10() + 
#   	theme_classic() +
#   	geom_vline(xintercept = 500) +
#   	geom_hline(yintercept = 250) +
#   	facet_wrap(~Sample_Tag)

subset_7271 %>% 
  	ggplot(aes(color=Sample_Tag, x=percent.mt, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)

```


```{r Visualize-qc-metrices-sample-7272, fig.cap="The figures show various QC metrices for sample 7272."}

subset_7272 %>% 
  	ggplot(aes(x=Sample_Tag, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

subset_7272 %>% 
  	ggplot(aes(color=Sample_Tag, x=nUMI, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

subset_7272 %>% 
  	ggplot(aes(color=Sample_Tag, x=nGene, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

# subset_7272 %>% 
#   	ggplot(aes(x=nUMI, y=nGene, color=Sample_Tag)) + 
#   	geom_point() + 
# 	scale_colour_gradient(low = "gray90", high = "black") +
#   	stat_smooth(method=lm) +
#   	scale_x_log10() + 
#   	scale_y_log10() + 
#   	theme_classic() +
#   	geom_vline(xintercept = 500) +
#   	geom_hline(yintercept = 250) +
#   	facet_wrap(~Sample_Tag)
# 
subset_7272 %>% 
  	ggplot(aes(color=Sample_Tag, x=percent.mt, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)
```

```{r Visualize-qc-metrices-sample-7273, fig.cap="The figures show various QC metrices for sample 7273."}

subset_7273 %>% 
  	ggplot(aes(x=Sample_Tag, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

subset_7273 %>% 
  	ggplot(aes(color=Sample_Tag, x=nUMI, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

subset_7273 %>% 
  	ggplot(aes(color=Sample_Tag, x=nGene, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)


# subset_7273 %>% 
#   	ggplot(aes(x=nUMI, y=nGene, color=Sample_Tag)) + 
#   	geom_point() + 
# 	scale_colour_gradient(low = "gray90", high = "black") +
#   	stat_smooth(method=lm) +
#   	scale_x_log10() + 
#   	scale_y_log10() + 
#   	theme_classic() +
#   	geom_vline(xintercept = 500) +
#   	geom_hline(yintercept = 250) +
#   	facet_wrap(~Sample_Tag)

subset_7273 %>% 
  	ggplot(aes(color=Sample_Tag, x=percent.mt, fill=Sample_Tag)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)

```

```{r Control-tags, fig.cap="The figures are showing different quality metrices for the control samples."}
#cell count
subset_control %>% 
  	ggplot(aes(x=seq_folder, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

#UMI count
subset_control %>% 
  	ggplot(aes(color=seq_folder, x=nUMI, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

#Gene Count
subset_control %>% 
  	ggplot(aes(color=seq_folder, x=nGene, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

#Mitochondrial count
subset_control %>% 
  	ggplot(aes(color=seq_folder, x=percent.mt, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)
```

```{r Copanlisib-tag, fig.cap="The figures are showing different quality metrices for the copanlisib samples."}
#cell count
subset_copanlisib %>% 
  	ggplot(aes(x=seq_folder, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

#UMI count
subset_copanlisib %>% 
  	ggplot(aes(color=seq_folder, x=nUMI, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

#Gene Count
subset_copanlisib %>% 
  	ggplot(aes(color=seq_folder, x=nGene, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

#Mitochondrial count
subset_copanlisib %>% 
  	ggplot(aes(color=seq_folder, x=percent.mt, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)
```

```{r Alpelisib-tag, fig.cap="The figures are showing different quality metrices for the alpelisib samples."}
#cell count
subset_alpelisib %>% 
  	ggplot(aes(x=seq_folder, fill=seq_folder)) + 
  	geom_bar() +
  	theme_classic() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells")

#UMI count
subset_alpelisib %>% 
  	ggplot(aes(color=seq_folder, x=nUMI, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	theme_classic() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)

#Gene Count
subset_alpelisib %>% 
  	ggplot(aes(color=seq_folder, x=nGene, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
  	theme_classic() +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)

#Mitochondrial count
subset_alpelisib %>% 
  	ggplot(aes(color=seq_folder, x=percent.mt, fill=seq_folder)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	theme_classic() +
  	geom_vline(xintercept = 2)
```

```{r set-threshold}
filtered_seurat <- subset(x = merged_seurat, 
                         subset= (nUMI >= 500) & 
                            (nGene >= 250) & 
                            (log10GenesPerUMI > 0.80) & 
                            (percent.mt < 5))
```

```{r}
# Extract counts
counts <- GetAssayData(object = filtered_seurat, slot = "counts")

# Output a logical matrix specifying for each gene on whether or not there are more than zero counts per cell
nonzero <- counts > 0
```

```{r}
# Sums all TRUE values and returns TRUE if more than 10 TRUE values per gene
keep_genes <- Matrix::rowSums(nonzero) >= 10

# Only keeping those genes expressed in more than 10 cells
filtered_counts <- counts[keep_genes, ]
```

```{r}
filtered_seurat <- CreateSeuratObject(filtered_counts, meta.data = filtered_seurat@meta.data)
```

```{r}
metadata_filtered <- filtered_seurat@meta.data
metadata_filtered[ , c("orig.ident", "nFeature_RNA", "nCount_RNA")] <- list(NULL)
#metadata_filtered <- metadata_filtered %>% drop_na()
filtered_seurat@meta.data <- metadata_filtered
```

```{r}
save(filtered_seurat, file="data/seuratmerged_filtered_tags.RData")
```