---
title: "Normalization and regressing out unwanted variation"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(ggsci)
```

```{r}
load("data/filtered_seurat_allcondition_mouse.RData")
```

```{r}
filtered_seurat_allcondition_mouse <- subset(filtered_seurat_allcondition_mouse, subset = Sample_Tag != "Undetermined")
```

```{r}
filtered_seurat_allcondition_mouse <- subset(filtered_seurat_allcondition_mouse, subset = Sample_Tag != "Multiplet")
```

```{r load-cell-cycle-markers}
load("data/cycle.rda")
```

```{r Score cells for cell cycle}
filtered_phase_seurat <- CellCycleScoring(filtered_seurat_allcondition_mouse, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)
```

```{r Identify the most variable genes}
filtered_phase_seurat <- FindVariableFeatures(filtered_phase_seurat,
                                     selection.method = "vst",
                                     nfeatures = 2000,
                                     verbose = FALSE)
```

```{r scale the counts}
filtered_phase_seurat <- ScaleData(filtered_phase_seurat)
```

```{r Perform PCA}
filtered_phase_seurat <- RunPCA(filtered_phase_seurat)
```

```{r Plot the PCA colored by cell cycle phase}
DimPlot(filtered_phase_seurat,
        reduction = "pca",
        group.by= "Phase",
        split.by = "Phase")+
  scale_fill_lancet()
```

```{r}
filtered_phase_seurat <- RunUMAP(filtered_phase_seurat,
                             dims = 1:40,
                             reduction = "pca")

```

```{r}
DimPlot(filtered_phase_seurat,
        reduction = "umap",
        split.by = "Phase",
        group.by = "Sample_Tag") + 
  ggtitle("UMAP splitted by cell cycle phase \n and grouped by conditions") + 
  scale_fill_lancet()
```

```{r}
FeaturePlot(filtered_phase_seurat,
            features = "percent.mt")+
   scale_fill_lancet()
```

```{r}
split_filtered_cond_seurat <- SplitObject(filtered_phase_seurat, split.by = "Sample_Tag")
```

```{r}
split_filtered_cond_seurat <- split_filtered_cond_seurat[c("Control", "Alpelisib", "Copanlisib")]
```

```{r}
saveRDS(split_filtered_cond_seurat, file="data/split_filtered_cond_seurat_mouse.rds")
```

```{r}
load("data/split_filtered_cond_seurat_mouse.rds")
```

```{r}
FeaturePlot(split_filtered_cond_seurat$Control,
            features = "percent.mt")+
   scale_fill_lancet()

FeaturePlot(split_filtered_cond_seurat$Alpelisib,
            features = "percent.mt")+
   scale_fill_lancet()

FeaturePlot(split_filtered_cond_seurat$Copanlisib,
            features = "percent.mt")+
   scale_fill_lancet()
```

```{r}
filtered_phase_meta <- filtered_phase_seurat@meta.data
```

```{r}
subset_control <- subset(filtered_phase_meta, filtered_phase_meta$Sample_Tag == "Control")
subset_alpelisib <- subset(filtered_phase_meta, filtered_phase_meta$Sample_Tag == "Alpelisib")
subset_copanlisib <- subset(filtered_phase_meta, filtered_phase_meta$Sample_Tag == "Copanlisib")
filtered_phase_meta <- subset(filtered_phase_meta, filtered_phase_meta$Sample_Tag == "Undetermined")
filtered_phase_meta <- subset(filtered_phase_meta, filtered_phase_meta$Sample_Tag == "Multiplet")
```

```{r}
subset_control %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    scale_fill_lancet()
```

```{r}
subset_alpelisib %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    scale_fill_lancet()
```

```{r}
subset_copanlisib %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    scale_fill_lancet()
```

```{r}
filtered_phase_meta %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    facet_grid(~seq_folder) +
    scale_fill_lancet()
```

```{r}
subset_control %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    facet_grid(~seq_folder)
    scale_fill_lancet()
  	
subset_copanlisib %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    facet_grid(~seq_folder) +
    scale_fill_lancet()
  	
subset_alpelisib %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    facet_grid(~seq_folder) +
    scale_fill_lancet()
```

```{r}
#split_filtered_cond_sct <- load("data/split_filtered_cond_seurat.rds")
split_filtered_sct_cond_seurat <- split_filtered_cond_seurat 
```

```{r}
for (i in 1:length(split_filtered_sct_cond_seurat)) {
    split_filtered_sct_cond_seurat[[i]] <- SCTransform(split_filtered_sct_cond_seurat[[i]])
    }
```

```{r}
saveRDS(split_filtered_sct_cond_seurat, file="data/split_filtered_sct_cond_seurat_mouse.rds")
```



```{r}
split_filtered_sct_mt_cond_seurat <- split_filtered_cond_seurat
  #load("data/split_filtered_seurat.rds")
```

```{r}
for (i in 1:length(split_filtered_sct_mt_cond_seurat)) {
    split_filtered_sct_mt_cond_seurat[[i]] <- SCTransform(split_filtered_sct_mt_cond_seurat[[i]], vars.to.regress = c("percent.mt"))
    }
```

```{r}
saveRDS(split_filtered_sct_mt_cond_seurat, file="data/split_filtered_sct_mt_cond_seurat_mouse.rds")
```



```{r}
split_filtered_sct_phase_cond_seurat <- split_filtered_cond_seurat 
  #load("data/split_filtered_seurat.rds")
```

```{r}
for (i in 1:length(split_filtered_sct_phase_cond_seurat)) {
    split_filtered_sct_phase_cond_seurat[[i]] <- SCTransform(split_filtered_sct_phase_cond_seurat[[i]], vars.to.regress = c("S.Score", "G2M.Score"))
    }
```

```{r}
saveRDS(split_filtered_sct_phase_cond_seurat, file="data/split_filtered_sct_phase_cond_seurat_mouse.rds")
```

```{r}
#load("data/split_filtered_cond_seurat")
```

```{r}
split_filtered_sct_mt_phase_cond_seurat <- split_filtered_cond_seurat 
```

```{r}
for (i in 1:length(split_filtered_sct_mt_phase_cond_seurat)) {
    split_filtered_sct_mt_phase_cond_seurat[[i]] <- SCTransform(split_filtered_sct_mt_phase_cond_seurat[[i]], vars.to.regress = c("S.Score", "G2M.Score", "percent.mt"))
    }
```

```{r}
saveRDS(split_filtered_sct_mt_phase_cond_seurat, file="data/split_filtered_sct_mt_phase_cond_seurat_mouse.rds")
```