---
title: "UMAP visualisation"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(rtracklayer)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(ggpubr)
library(cowplot)
library(dplyr)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
library(SingleCellExperiment)
library(scales)
library(RCurl)
library(M3C)
source("helperFunctions.R")
```

```{r load-data}
integrated_seurat <- readRDS("data/integrated_seurat.rds")
```

```{r create-metadata-df}
integrated_seurat <- subset(integrated_seurat, subset = Sample_Tag != "NA")
#DefaultAssay(integrated_seurat) <- "RNA"
#colSums(is.na(subset_pilots@meta.data))
```

```{r subset metadata for UMAP}
subset_pilots <- subset(integrated_seurat, seq_folder == "1820" | seq_folder == "1822")
subset_1820 <- subset(integrated_seurat, seq_folder == "1820")
subset_70_71 <- subset(integrated_seurat, seq_folder == "7270" | seq_folder == "7271")
subset_7272 <- subset(integrated_seurat, seq_folder == "7272")
subset_7273 <- subset(integrated_seurat, seq_folder == "7273")
subset_control <- subset(integrated_seurat, Sample_Tag == "Control")
subset_alpelisib <- subset(integrated_seurat, Sample_Tag == "Alpelisib")
subset_copanlisib <- subset(integrated_seurat, Sample_Tag == "Copanlisib")
```

```{r UMAP-all-samples}
DimPlot(integrated_seurat, group.by = "Sample_Tag") +
  labs(title = "UMAP showing all samples \n grouped by their sample tags")
```

```{r tbl-cells-per-cluster-sampletag}
# Extract identity and sample information from seurat object to determine the number of cells per cluster per sample_tag
n_cells <- FetchData(integrated_seurat, 
                     vars = c("ident", "Sample_Tag")) %>%
        dplyr::count(ident, Sample_Tag) %>%
        tidyr::spread(ident, n)

# View table
View(n_cells)

datatable(n_cells,
          caption = "The table shows the number of cells per cluster per sample tag")

```

```{r UMAP-1820-sample}
DimPlot(subset_1820, 
        split.by = "Sample_Tag",
        group.by = "Phase") +
  labs(title = "UMAP 1820 sample tags combined \n with cell cycle phases",
       caption = "Sample 1820 grouped by the cell cycle phases and splitted by the different sample tags.") +
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_1820,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all sample tags from sample 1820.")

```

```{r UMAP-pilot-sample}
DimPlot(subset_pilots, 
        split.by = "Sample_Tag", 
        group.by = "Phase") +
  labs(title = "UMAP HN15239 sample tags combined \n with cell cycle phases",
       caption = "HN15239 grouped by the cell cycle phases and splitted by the different sample tags.")+
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_pilots,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all sample tags from HN15239.")
```

```{r UMAP-7273-sample}
DimPlot(subset_7273, 
        split.by = "Sample_Tag", 
        group.by = "Phase")+
  labs(title = "UMAP HN10621 sample tags combined \n with cell cycle phases",
       caption = "HN10621 grouped by the cell cycle phases and splitted by the different sample tags.") +
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_7273,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all sample tags from HN10621.")
```

```{r UMAP-7271-7270-sample}
DimPlot(subset_70_71,
        split.by = "Sample_Tag",
        group.by = "Phase") +
  labs(title = "UMAP HN11097 sample tags combined \n with cell cycle phases",
       caption = "HN11097 grouped by the cell cycle phases and splitted by the different sample tags.")+
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_70_71,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all sample tags from HN11097.")
```

```{r UMAP-7272-sample}
DimPlot(subset_7272,
        split.by = "Sample_Tag",
        group.by = "Phase") +
  labs(title = "UMAP HN10960 sample tags combined \n with cell cycle phases",
       caption = "HN10960 grouped by the cell cycle phases and splitted by the different sample tags.") +
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_7272,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all sample tags from HN10960.")
```

```{r UMAP-control-sample}
DimPlot(subset_control,
        split.by = "Sample_Tag",
        group.by = "Phase") +
  labs(title = "UMAP control sample tags combined \n with cell cycle phases",
       caption = "UMAP grouped by the cell cycle phases and splitted by control sample tags.")+
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_control,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all control sample tags.")
```

```{r UMAP-alpelisib-sample}
DimPlot(subset_alpelisib,
        split.by = "Sample_Tag",
        group.by = "Phase") +
  labs(title = "UMAP alpelisib sample tags combined \n with cell cycle phases",
       caption = "UMAP grouped by the cell cycle phases and splitted by the alpelisib sample tags.")+
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_alpelisib,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all alpelisib sample tags.")
```

```{r UMAP-copanlisib-sample}
DimPlot(subset_copanlisib,
        split.by = "Sample_Tag",
        group.by = "Phase") +
  labs(title = "UMAP copanslisib sample tags combined \n with cell cycle phases",
       caption = "UMAP grouped by the cell cycle phases and splitted by the copanlisib sample tags.")+
  theme(plot.caption = element_text(hjust = 0.5))

DimPlot(subset_copanlisib,
        group.by = "Sample_Tag") +
  labs(title = "UMAP visualisation of \n all copanlisib sample tags.")
```