---
title: "UMAP visualisation with cell cycle effects & mt.genes regressed out"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(Seurat)
library(knitr)
library(janitor)
library(ggsci)
library(cowplot)
library(dplyr)
library(DT)
library(biomaRt)
library(gplots)
library(clusterProfiler)
library(org.Hs.eg.db)
library(SingleCellExperiment)
library(scales)
library(RCurl)
library(M3C)
#source("helperFunctions.R")
```

```{r load data}
load("data/seuratmerged_filtered_tags.RData")
#colSums(is.na(filtered_seurat@meta.data))
#filtered_seurat <- subset(filtered_seurat, subset = Sample_Tag != "NA")
#colSums(is.na(filtered_seurat@meta.data))
```

```{r normalize-counts}
seurat_phase <- NormalizeData(filtered_seurat)
```

```{r load-cell-cycle-markers}
load("data/cycle.rda")
```

```{r Score cells for cell cycle}
seurat_phase <- CellCycleScoring(seurat_phase, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)
```

```{r Identify the most variable genes}
seurat_phase <- FindVariableFeatures(seurat_phase,
                                     selection.method = "vst",
                                     nfeatures = 2000,
                                     verbose = FALSE)
```

```{r}
#options(future.globals.maxSize = 850*1024^2)
```

```{r scale the counts}

seurat_phase_regressed <- ScaleData(seurat_phase)

# seurat_phase_regressed <- ScaleData(seurat_phase,
#                                    vars.to.regress = c("S.Score", "G2M.Score"),
#                                    features = rownames(seurat_phase))


#seurat_phase@meta.data$CC.Difference <- seurat_phase@meta.data$S.Score - seurat_phase@meta.data$G2M.Score
#seurat_phase_regressed <- ScaleData(seurat_phase,
#                                    vars.to.regress = "CC.Difference",
#                                    features = rownames(seurat_phase))
```

```{r}
#saveRDS(seurat_phase_regressed, file="data/regressed_seurat.rds")
```

```{r}
#seurat_phase_regressed <- readRDS("data/regressed_seurat.rds")
```

```{r}
seurat_phase_regressed <- RunPCA(seurat_phase_regressed)
```

```{r Plot the PCA colored by cell cycle phase}
DimPlot(seurat_phase_regressed,
        reduction = "pca",
        group.by= "Phase",
        split.by = "Phase")
```

```{r}
seurat_phase_regressed_UMAP <- RunUMAP(seurat_phase_regressed,
                              dims = 1:40,
                              reduction = "pca")
```

```{r}
# Plot UMAP                             
DimPlot(seurat_phase_regressed_UMAP,
        reduction = "umap",
        split.by = "Sample_Tag",
        group.by = "Phase")   
```

```{r split seurat object by condition to perform cell cycle scoring and SCT on all samples}
split_seurat_regressed <- SplitObject(seurat_phase_regressed, split.by = "Sample_Tag")
```

```{r}
split_seurat_regressed <- split_seurat_regressed[c("1820", "1822", "7270", "7271", "7272", "7273")]
```

```{r}
for (i in 1:length(split_seurat_regressed)) {
    split_seurat_regressed[[i]] <- SCTransform(split_seurat_regressed[[i]], vars.to.regress = c("percent.mt", "S.Score", "G2M.Score"))
    }
```

```{r}
saveRDS(split_seurat_regressed, file="data/split_seurat_regressed.rds")
```
