---
title: "Normalization"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(dplyr)
library(ggsci)
```

```{r}
load("E://CCCC/PI3K/data/SeuratObjects/filtered/Human/filtered_seurat.RData")
filtered_seurat$nCount_RNA <- NULL
filtered_seurat$nFeature_RNA <- NULL
filtered_seurat$orig.ident <- NULL
```

```{r load-cell-cycle-markers}
load("E://CCCC/PI3K/data/SuplementaryFiles/SeuratObjects/cycle.rda")
```

```{r Score cells for cell cycle}
filtered_phase_seurat <- CellCycleScoring(filtered_seurat, 
                                 g2m.features = g2m_genes, 
                                 s.features = s_genes)
```

```{r Identify the most variable genes}
filtered_phase_seurat <- FindVariableFeatures(filtered_phase_seurat,
                                     selection.method = "vst",
                                     nfeatures = 2000,
                                     verbose = FALSE)
```

```{r scale the counts}
filtered_phase_seurat <- ScaleData(filtered_phase_seurat)
```

```{r Perform PCA}
filtered_phase_seurat <- RunPCA(filtered_phase_seurat)
```

```{r Plot the PCA colored by cell cycle phase}
DimPlot(filtered_phase_seurat,
        reduction = "pca",
        group.by= "Phase",
        split.by = "Phase")+
  ggtitle("PCA visualization of the cell cycle phases")+
  scale_fill_lancet()
```

```{r}
filtered_phase_seurat <- RunUMAP(filtered_phase_seurat,
                             dims = 1:40,
                             reduction = "pca")

```

```{r}
DimPlot(filtered_phase_seurat,
        reduction = "umap",
        split.by = "Phase",
        group.by = "Sample_Tag") + 
  ggtitle("UMAP splitted by cell cycle phase \n and grouped by conditions") + 
  scale_fill_lancet()
```
```{r}
FeaturePlot(filtered_phase_seurat,
            features = "percent.mt")+
   ggtitle("Mitochondrial gene expression distribution in clusters")+
   scale_fill_lancet()
```

```{r}
split_filtered_cond_seurat <- SplitObject(filtered_phase_seurat, split.by = "Sample_Tag")
```

```{r}
split_filtered_cond_seurat <- split_filtered_cond_seurat[c("Control", "Alpelisib", "Copanlisib")]
```

```{r}
saveRDS(split_filtered_cond_seurat, file="E://CCCC/PI3K/data/SeuratObjects/splitted/Human/split_filtered_cond_seurat.rds")
```

```{r}
FeaturePlot(split_filtered_cond_seurat$Control,
            features = "percent.mt")+
   labs(title="Overview over the mitochondrial gene expression \n in the control group")+
   scale_fill_lancet()

FeaturePlot(split_filtered_cond_seurat$Alpelisib,
            features = "percent.mt")+
  labs(title="Overview over the mitochondrial gene expression \n with the alpelisib treatment")+
  scale_fill_lancet()

FeaturePlot(split_filtered_cond_seurat$Copanlisib,
            features = "percent.mt")+
  labs(title="Overview over the mitochondrial gene expression \n with the copanlisib treatment")+
  scale_fill_lancet()
```

```{r}
filtered_phase_meta <- filtered_phase_seurat@meta.data
```

```{r}
filtered_phase_meta %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    labs(x="Cell cycle phases ", y="Number of cells",
             title="Overview of the number of cells by cell cycle phases per Xenograft") +
    facet_grid(~Xenograft) +
    scale_fill_lancet(name="Condition")
```

```{r}
filtered_phase_meta %>% 
  	ggplot(aes(x=Phase, fill=Sample_Tag)) + 
  	geom_bar() +
    labs(x="Cell cycle phases ", y="Number of cells",
             title="Overview of the number of cells by cell cycle phases per xenograft \n and condition") +
    facet_grid(Sample_Tag~Xenograft) +
    scale_fill_lancet(name="Condition")
```

```{r}
#split_filtered_cond_sct <- load("E://CCCC/PI3K/data/SeuratObjects/splitted/Human/split_filtered_cond_seurat.rds")
split_filtered_sct_cond_seurat <- split_filtered_cond_seurat 
```

```{r}
for (i in 1:length(split_filtered_sct_cond_seurat)) {
    split_filtered_sct_cond_seurat[[i]] <- SCTransform(split_filtered_sct_cond_seurat[[i]])
    }
```

```{r}
saveRDS(split_filtered_sct_cond_seurat, file="E://CCCC/PI3K/data/SeuratObjects/sct_normalized/Human/split_filtered_sct_cond_seurat.rds")
```