---
title: "Celltype Identification singlR human"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(ggsci)
library(SingleR)
library(caret)
library(multtest)
library(clustree)
library(limma)
library(readxl)
```

```{r load-seurat-object}
seurat_integrated_newidents <- readRDS("E://CCCC/PI3K/data/SeuratObjects/clusteranalysis/Human/seurat_integrated_newidents.rds")
```

```{r get-humanPrimaryCellAtlasAnnotationdata}
ref <- celldex::HumanPrimaryCellAtlasData()
```

```{r annotating-data-with-SingleR-method}
results_main <- SingleR(test = as.SingleCellExperiment(seurat_integrated_newidents), ref = ref, labels = ref$label.main)
```

```{r adding-singleR-labels-to-seuratObject}
seurat_integrated_newidents@meta.data$singlr_labels <- results_main$labels
```

```{r assing-the-0.4-resolution-as-Indentifier}
Idents(object = seurat_integrated_newidents) <- "integrated_snn_res.0.4"
```

```{r}
metadata <- seurat_integrated_newidents@meta.data
```

```{r}
resolution.04 <- metadata %>%
  group_by(integrated_snn_res.0.4) %>%
 summarise(max = max(singlr_labels))

show(resolution.04)
```
```{r}
#Extract identity and sample information from seurat object to determine the number of cells per cluster per sample
n_cells0.4 <- FetchData(seurat_integrated_newidents,
                     vars = c("integrated_snn_res.0.4", "singlr_labels")) %>%
        dplyr::count(integrated_snn_res.0.4, singlr_labels) %>%
        tidyr::spread(integrated_snn_res.0.4, n)

# View table
View(n_cells0.4)

```

```{r}
seurat_integrated_renameidents <- RenameIdents(object = seurat_integrated_newidents,
                                    "0" = "Gametocytes",
                                    "1" = "Erythroblast",
                                    "2" = "Gametocytes",
                                    "3" = "Gametocytes",
                                    "4" = "Gametocytes",
                                    "5" = "Gametocytes",
                                    "6" = "Fibroblasts",
                                    "7" = "Fibroblasts",
                                    "8" = "Gametocytes",
                                    "9" = "Neuroepithelial_cell",
                                    "10" = "Keratinocytes",
                                    "11" = "B_cell")

DimPlot(object = seurat_integrated_renameidents, 
        reduction = "umap", 
        label = TRUE,
        label.size = 3,
        repel = TRUE) +
        labs(title = "UMAP visualisation shows the different celltypes \n for the resolution 0.4") +
        scale_fill_lancet(name="Celltypes")
```

```{r}
n_cells0.4.long <- pivot_longer(n_cells0.4, cols="0":"11", names_to = "ClusterID", values_to = "Occurances", values_drop_na = TRUE)
```

```{r}
plt_0.4 <- ggplot(n_cells0.4.long,aes(ClusterID, singlr_labels)) +
  geom_tile(aes(fill=Occurances)) +  
  geom_text(aes(label = round(Occurances, 1)), size=2) +
  scale_fill_gradient(low = "white", high = "red") +
  labs(y="Celltypes")

plt_0.4
```
```{r}
saveRDS(seurat_integrated_renameidents, "E://CCCC/PI3K/data/SeuratObjects/celltypeIdentification/Human/SingleR/seurat_integrated_singleR.rds")
```
