---
title: "Cellfiltering_based_on_umis"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(ggsci)
library(SingleR)
library(caret)
library(multtest)
library(clustree)
library(limma)
library(readxl)
library(stats)
```

```{r load data}
seurat_integrated <- readRDS("E://CCCC/PI3K/data/SeuratObjects/clusteranalysis/Human/seurat_integrated_newidents.rds")
seurat_integrated_mouse <- readRDS("E://CCCC/PI3K/data/SeuratObjects/clusteranalysis/Mouse/seurat_integrated_newidents.rds")
umi_counts_merged <- read_delim("E://CCCC/PI3K/data/SuplementaryFiles/CSVFiles/umi_count_merged.csv")
puram_sct <- readRDS("E://CCCC/PI3K/data/SeuratObjects/sct_normalized/Human/puram_seurat_sct.rds")
```

```{r filter umi_counts_merged_filtering}
umi_counts_merged_combined_mouse <- subset(umi_counts_merged, umi_counts_merged$Labels == "unique_mouse" | umi_counts_merged$Labels == "mainly_mouse" |  umi_counts_merged$Labels == "mainly_human")
umi_counts_merged_combined_mouse %>% select(-2,-3) -> umi_counts_merged_combined_mouse

umi_counts_merged_combined <- subset(umi_counts_merged, umi_counts_merged$Labels == "unique_human" | umi_counts_merged$Labels == "mainly_human" | umi_counts_merged$Labels == "mainly_mouse")
umi_counts_merged_combined %>% select(-2,-3) -> umi_counts_merged_combined
```


```{r subset seurat_objects}
#subset seurat objects based on filtered cells
seurat_integrated <- AddMetaData(seurat_integrated, umi_counts_merged_combined$Labels, col.name = "Labels")
seurat_integrated_mouse <- AddMetaData(seurat_integrated_mouse, umi_counts_merged_combined_mouse$Labels, col.name = "Labels")

#subset Seurat
seurat_integrated_filtered_human <- subset(seurat_integrated, subset=Labels != "unique_mouse")
seurat_integrated_filtered_mouse <- subset(seurat_integrated_mouse, subset= Labels != "unique_human")

saveRDS(seurat_integrated,"E://CCCC/PI3K/data/SeuratObjects/cellfiltering_umi/Human/seurat_integrated_with_spec_labels.rds")
saveRDS(seurat_integrated_mouse,"E://CCCC/PI3K/data/SeuratObjects/cellfiltering_umi/Mouse/seurat_integrated_with_spec_labels_mouse.rds")
saveRDS(seurat_integrated_filtered_human,"E://CCCC/PI3K/data/SeuratObjects/demultiplexed/Human/seurat_integrated_filtered_human.rds")
saveRDS(seurat_integrated_filtered_mouse,"E://CCCC/PI3K/data/SeuratObjects/demultiplexed/Mouse/seurat_integrated_filtered_mouse.rds")

```

```{r}
UMAP_human <- DimPlot(seurat_integrated, reduction = "umap", group.by= "Labels", cols = c("red","lightgrey","purple")) + ggtitle("UMAP human cells")
UMAP_mouse <- DimPlot(seurat_integrated_mouse, reduction = "umap", group.by = "Labels", cols = c("red", "grey", "lightgrey")) + ggtitle("UMAP mouse cells")
UMAP_human
UMAP_mouse
```

```{r}
seurat_integrated_filtered_human <- RunUMAP(seurat_integrated_filtered_human, dims = 1:30)
DimPlot(seurat_integrated_filtered_human, reduction = "umap", group.by = "Sample_Tag") + ggtitle("UMAP human cells by conditions")

seurat_integrated_filtered_mouse <- RunUMAP(seurat_integrated_filtered_mouse, dims = 1:30)
DimPlot(seurat_integrated_filtered_mouse, reduction = "umap", group.by = "Sample_Tag") + ggtitle("UMAP mouse cells by conditions")
```
```{r}
metadata <- seurat_integrated@meta.data
metadata %>% select(2,26) -> metadata
table(metadata)
prop.table(table(metadata))
```

```{r}
metadata_mouse <- seurat_integrated_mouse@meta.data
metadata_mouse %>% select(2,26) -> metadata_mouse
table(metadata_mouse)
prop.table(table(metadata_mouse))
```