---
title: "SingleR label comparison between human and mouse"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(ggsci)
library(SingleR)
library(caret)
library(multtest)
library(clustree)
library(limma)
library(readxl)
```

```{r}
integrated_seurat <- readRDS("E://CCCC/PI3K/data/SeuratObjects/celltypeIdentification/Human/SingleR/seurat_integrated_singleR.rds")
integrated_Seurat_mouse <- readRDS("E://CCCC/PI3K/data/SeuratObjects/celltypeIdentification/Mouse/SingleR/seurat_integrated_singleR.rds")
```

```{r}
metadata <- integrated_seurat@meta.data
metadata_mouse <- integrated_Seurat_mouse@meta.data

human_meta <- metadata[,c("Cell_Index", "singlr_labels")]
human_meta

mouse_meta <- metadata_mouse[,c("Cell_Index", "singlr_labels")]
mouse_meta
```

```{r}
df_merged <- merge(human_meta, mouse_meta, by= c("Cell_Index"), all = TRUE)
df_merged <- rename(df_merged, c("singlr_labels.x" = "singlr_labels.human", "singlr_labels.y" = "singlr_labels.mouse"))
df_merged$singlr_labels.human <- df_merged$singlr_labels.human %>% replace_na("unmatched") 
df_merged$singlr_labels.mouse <- df_merged$singlr_labels.mouse %>% replace_na("unmatched")

show(df_merged)
```

```{r}
df_merged <- aggregate(df_merged$Cell_Index, by =list(df_merged$singlr_labels.human,df_merged$singlr_labels.mouse), FUN=length)
df_merged <- rename(df_merged, c("Group.1" = "singlr_labels.human", "Group.2" = "singlr_labels.mouse", "x" = "Cell_Index_count"))
show(df_merged)
```

```{r}
plt_merged <- ggplot(df_merged,aes(x = singlr_labels.human, y= singlr_labels.mouse)) +
  geom_tile(aes(fill=Cell_Index_count)) +
  geom_text(aes(label = Cell_Index_count), size=1.5) +
  scale_fill_gradient(low = "white", high = "red") +
  labs(x="Celltypes_human", y="Celltypes_mouse") +
  theme(axis.text.x = element_text(angle=90))

plt_merged
saveRDS(df_merged, "E://CCCC/PI3K/data/SeuratObjects/celltypeIdentification/df_merged_singleR_labels.rds")
```