samples:
  #1820_R1: fast/users/${USER}/work/PIP3K/samples/raw_data/R1820/{id}*_R1_001.fastq
  #1820_R2: fast/users/${USER}/work/PIP3K/samples/raw_data/R1820/{id}*_R2_001.fastq
  #1822_R1: fast/users/${USER}/work/PIP3K/samples/raw_data/R1822/{id2}*_R1_001.fastq
  #1822_R2: fast/users/${USER}/work/PIP3K/samples/raw_data/R1822/{id2}*_R2_001.fastq
  1820_trimmed: /fast/users/elismaim_c/scratch/tmp/R1820/trimmed_reads/{id}*_R2.fastq_trimmed.fastq
  1822_trimmed: /fast/users/elismaim_c/scratch/tmp/R1820/trimmed_reads/{id2}*_R2.fastq_trimmed.fastq
