
configfile: "/fast/users/elismaim_c/scratch/tmp/PI3K/Snakemake/config.yaml"
print (config['samples'])


rule all:
    input:
        expand("$TMPDIR/{sample}_{num}_cleaned.fastq", sample=config["samples"], num=['1','2','3','4','5','6','7','8']),
        expand("$TMPDIR/{sample}_{num}_out_%.sam", sample=config["samples"], num=['1','2','3','4','5','6','7','8'])

rule bbsplit:
    input:
        sample = lambda wildcards: f"{config['samples'][wildcards.sample]}_{wildcards.num}.fastq"
    output:
        R_cleaned="$TMPDIR/{sample}_{num}_cleaned.fastq",
        sam = "$TMPDIR/{sample}_{num}_out_%.sam"
    params:
        mouse_ref="$REFDIRM/GRCm38.primary_assembly.genome.fa",
        human_ref="$REFDIRH/GRCh38.primary_assembly.genome.fa"
    shell:
        """     
        cd $TMPDIR
        bbsplit.sh in={input} ref={params.mouse_ref},{params.human_ref} \
        minratio=0.56 minhits=1 maxindel=16000 \
        basename={wildcards.sample}_out_%.sam out={output.R_cleaned} ambig2=all \
        """





