---
title: "Clustering different Resolutions"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

```{r load-libraries}
library(Seurat)
library(tidyverse)
library(RCurl)
library(cowplot)
library(dplyr)
library(ggsci)
library(SingleR)
library(caret)
library(multtest)
library(clustree)
library(limma)
```

```{r}
integrated_filtered_sct_cond_seurat <- readRDS("E://CCCC/PI3K/data/SeuratObjects/integrated/Mouse/integrated_filtered_sct_cond_seurat.rds")
```

```{r}
# Determine the clusters for various resolutions                                
seurat_integrated <- FindClusters(object = integrated_filtered_sct_cond_seurat,
                               resolution = c(0.2, 0.4, 0.6, 0.8, 1.0, 1.4, 1.6, 1.8, 2.0, 2.4))
```

```{r}
# Explore resolutions
seurat_integrated@meta.data %>% 
        View()
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.1"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6) +
        labs(title = "UMAP visualisation shows the number of clusters \n for resolution 1.0") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.0.2"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 0.2") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.0.4"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 0.4") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.0.6"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 0.6") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.0.8"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 0.8") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.1.4"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 1.4") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.1.6"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 1.6") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.1.8"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 1.8") +
        scale_fill_lancet(name="ClusterIDs")
```

```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.2"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 2.0") +
        scale_fill_lancet(name="ClusterIDs")
```


```{r}
# Assign identity of clusters
Idents(object = seurat_integrated) <- "integrated_snn_res.2.4"
```

```{r}
# Plot the UMAP
DimPlot(seurat_integrated,
        reduction = "umap",
        label = TRUE,
        label.size = 6)+
        labs(title = "UMAP visualisation shows the number of clusters \n for the resolution 2.4") +
        scale_fill_lancet(name="ClusterIDs")
```
```{r}
# Assign identity of clusters which we are using in the following analysis
Idents(object = seurat_integrated) <- "integrated_snn_res.0.4"
```

```{r}
saveRDS(seurat_integrated, file="E://CCCC/PI3K/data/SeuratObjects/clusteranalysis/Mouse/seurat_integrated_newidents.rds")
```