---
title: "Demultiplexing"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
bibliography: literature.bib
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load libraries
library(SingleCellExperiment)
library(Seurat)
library(tidyverse)
library(Matrix)
library(scales)
library(cowplot)
library(RCurl)
```

```{r}
# Load Seurat_objects
load("E://CCCC/PI3K/data/SeuratObjects/unfiltered/Mouse/unfilteredSeurat_1820_mouse.Rdata")
load("E://CCCC/PI3K/data/SeuratObjects/unfiltered/Mouse/unfilteredSeurat_1822_mouse.Rdata")
load("E://CCCC/PI3K/data/SeuratObjects/unfiltered/Mouse/unfilteredSeurat_7270_mouse.Rdata")
load("E://CCCC/PI3K/data/SeuratObjects/unfiltered/Mouse/unfilteredSeurat_7271_mouse.Rdata")
load("E://CCCC/PI3K/data/SeuratObjects/unfiltered/Mouse/unfilteredSeurat_7272_mouse.Rdata")
load("E://CCCC/PI3K/data/SeuratObjects/unfiltered/Mouse/unfilteredSeurat_7273_mouse.Rdata")
```

```{r}
# prepare Seurat_objects 
# sample 1820
metadata_1820 <- list_seurat_1820m$`1820`@meta.data
metadata_1820$Cell_Index <- rownames(metadata_1820)
metadata_1820$Cell_Index <- str_remove_all(metadata_1820$Cell_Index, "[Cell_Index]")
metadata_1820$Cell_Index <- paste0("1820_Cell_Index", metadata_1820$Cell_Index)
rownames(metadata_1820) <- metadata_1820$Cell_Index
metadata_1820$orig.ident <- ("1820")

st.1820 <- read_csv("E://CCCC/PI3K/data/SuplementaryFiles/SampleTags/1820_Sample_Tag_Calls.csv", comment = "##") %>% dplyr::select(-Sample_Name)
st.1820$Cell_Index <- paste0("1820_Cell_Index", st.1820$Cell_Index)
rownames(st.1820) <- st.1820$Cell_Index
st.1820$orig.ident <- ("1820")
st.1820$Sample_Tag[which(str_detect(st.1820$Sample_Tag, "SampleTag01_hs"))] <- "Control" #Control_tagged
st.1820$Sample_Tag[which(str_detect(st.1820$Sample_Tag, "Undetermined"))] <- "Control"

metadata1820_merged <- merge(metadata_1820, st.1820, by = c("Cell_Index", "orig.ident"), all.x=TRUE)
rownames(metadata1820_merged) <- metadata1820_merged$Cell_Index
list_seurat_1820m$`1820`@meta.data <- metadata1820_merged
```

```{r}
# sample 1822
metadata_1822 <- list_seurat_1822m$`1822`@meta.data
metadata_1822$Cell_Index <- rownames(metadata_1822)
metadata_1822$Cell_Index <- str_remove_all(metadata_1822$Cell_Index, "[Cell_Index]")
metadata_1822$Cell_Index <- paste0("1822_Cell_Index", metadata_1822$Cell_Index)
rownames(metadata_1822) <- metadata_1822$Cell_Index
metadata_1822$Sample_Tag <- c("Alpelisib")
metadata_1822$orig.ident <- ("1822")

list_seurat_1822m$`1822`@meta.data <- metadata_1822
```

```{r}
# sample 7270
metadata_7270 <- list_seurat_7270m$`7270`@meta.data
metadata_7270$Cell_Index <- rownames(metadata_7270)
metadata_7270$Cell_Index <- str_remove_all(metadata_7270$Cell_Index, "[Cell_Index]")
metadata_7270$Cell_Index <- paste0("7270_Cell_Index", metadata_7270$Cell_Index)
rownames(metadata_7270) <- metadata_7270$Cell_Index
metadata_7270$orig.ident <- ("7270")

st.7270 <- read_csv("E://CCCC/PI3K/data/SuplementaryFiles/SampleTags/7270_Sample_Tag_Calls.csv", comment = "##") %>% dplyr::select(-Sample_Name)
st.7270$Cell_Index <- paste0("7270_Cell_Index", st.7270$Cell_Index)
rownames(st.7270) <- st.7270$Cell_Index
st.7270$orig.ident <- ("7270")
st.7270$Sample_Tag[which(str_detect(st.7270$Sample_Tag, "SampleTag02_hs"))] <- "Copanlisib"
st.7270$Sample_Tag[which(str_detect(st.7270$Sample_Tag, "SampleTag03_hs"))] <- "Alpelisib"

metadata7270_merged <- merge(metadata_7270, st.7270, by = c("Cell_Index", "orig.ident"), all.x=TRUE)
rownames(metadata7270_merged) <- metadata7270_merged$Cell_Index
list_seurat_7270m$`7270`@meta.data <- metadata7270_merged
```

```{r}
#sample 7271
metadata_7271 <- list_seurat_7271m$`7271`@meta.data
metadata_7271$Cell_Index <- rownames(metadata_7271)
metadata_7271$Cell_Index <- str_remove_all(metadata_7271$Cell_Index, "[Cell_Index]")
metadata_7271$Cell_Index <- paste0("7271_Cell_Index", metadata_7271$Cell_Index)
rownames(metadata_7271) <- metadata_7271$Cell_Index
metadata_7271$orig.ident <- ("7271")

st.7271 <- read_csv("E://CCCC/PI3K/data/SuplementaryFiles/SampleTags/7271_Sample_Tag_Calls.csv", comment = "##") %>% dplyr::select(-Sample_Name)
st.7271$Cell_Index <- paste0("7271_Cell_Index", st.7271$Cell_Index)
rownames(st.7271) <- st.7271$Cell_Index
st.7271$orig.ident <- ("7271")
st.7271$Sample_Tag[which(str_detect(st.7271$Sample_Tag, "Undetermined"))] <- "Control" #Control_tagged

metadata7271_merged <- merge(metadata_7271, st.7271, by = c("Cell_Index", "orig.ident"), all.x=TRUE)
rownames(metadata7271_merged) <- metadata7271_merged$Cell_Index
list_seurat_7271m$`7271`@meta.data <- metadata7271_merged
```

```{r}
# sample 7272
metadata_7272 <- list_seurat_7272m$`7272`@meta.data
metadata_7272$Cell_Index <- rownames(metadata_7272)
metadata_7272$Cell_Index <- str_remove_all(metadata_7272$Cell_Index, "[Cell_Index]")
metadata_7272$Cell_Index <- paste0("7272_Cell_Index", metadata_7272$Cell_Index)
rownames(metadata_7272) <- metadata_7272$Cell_Index
metadata_7272$Sample_Tag <- c("Control")
metadata_7272$orig.ident <- ("7272")

list_seurat_7272m$`7272`@meta.data <- metadata_7272
```

```{r}
#sample 7273
metadata_7273 <- list_seurat_7273m$`7273`@meta.data
metadata_7273$Cell_Index <- rownames(metadata_7273)
metadata_7273$Cell_Index <- str_remove_all(metadata_7273$Cell_Index, "[Cell_Index]")
metadata_7273$Cell_Index <- paste0("7273_Cell_Index", metadata_7273$Cell_Index)
rownames(metadata_7273) <- metadata_7273$Cell_Index
metadata_7273$orig.ident <- ("7273")

st.7273 <- read_csv("E://CCCC/PI3K/data/SuplementaryFiles/SampleTags/7273_Sample_Tag_Calls.csv", comment = "##") %>% dplyr::select(-Sample_Name)
st.7273$Cell_Index <- paste0("7273_Cell_Index", st.7273$Cell_Index)
rownames(st.7273) <- st.7273$Cell_Index
st.7273$orig.ident <- ("7273")
st.7273$Sample_Tag[which(str_detect(st.7273$Sample_Tag, "SampleTag03_hs"))] <- "Copanlisib"
st.7273$Sample_Tag[which(str_detect(st.7273$Sample_Tag, "Undetermined"))] <- "Control"
st.7273$Sample_Tag[which(str_detect(st.7273$Sample_Tag, "SampleTag02_hs"))] <- "Alpelisib"

metadata7273_merged <- merge(metadata_7273, st.7273, by = c("Cell_Index", "orig.ident"), all.x=TRUE)
rownames(metadata7273_merged) <- metadata7273_merged$Cell_Index
list_seurat_7273m$`7273`@meta.data <- metadata7273_merged
```

```{r}
##merged objects
merged_seurat <- merge(x = list_seurat_1820m[[1]], 
                       y = c(list_seurat_1822m[[1]],list_seurat_7270m[[1]],list_seurat_7271m[[1]],list_seurat_7272m[[1]],list_seurat_7273m[[1]]),
                       add.cell.ids = c("1820", "1822", "7270", "7271", "7272", "7273"), project = "HNSCC")

```

```{r}
# Add number of genes per UMI for each cell to metadata
merged_seurat$log10GenesPerUMI <- log10(merged_seurat$nFeature_RNA) / log10(merged_seurat$nCount_RNA)
```

```{r}
metadata <- merged_seurat@meta.data
```

```{r}
metadata <- metadata %>% 
  dplyr::rename(Xenograft = orig.ident,
                nUMI = nCount_RNA,
                nGene = nFeature_RNA)
```

```{r}
metadata["Xenograft"][metadata["Xenograft"] == "1820"] <- "HN15239A_Control"
metadata["Xenograft"][metadata["Xenograft"] == "1822"] <- "HN15239A_Alpelisib"
metadata["Xenograft"][metadata["Xenograft"] == "7270"] <- "HN11097_treated"
metadata["Xenograft"][metadata["Xenograft"] == "7271"] <- "HN11097_Control"
metadata["Xenograft"][metadata["Xenograft"] == "7272"] <- "HN10960"
metadata["Xenograft"][metadata["Xenograft"] == "7273"] <- "HN10621"
```

```{r}
merged_seurat@meta.data <- metadata
```

```{r}
save(merged_seurat, file="E://CCCC/PI3K/data/SeuratObjects/merged/Mouse/merged_seurat_mouse.RData")
```
