---
title: "Quality control & cell filtering"
description: |
  Overview of data analysis.
author:
  - name: Manuela Benary / Mohammad El-Ismail
    affiliation: CUBI / CCCC
    affiliation_url: 
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
    toc_depth: 2
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r load-libraries}
library(Matrix)
library(Matrix.utils)
library(tidyverse)
library(Seurat)
library(dplyr)
library(knitr)
library(ggsci)
```

```{r load-merged-seuratobject}
load("E://CCCC/PI3K/data/SeuratObjects/merged/Mouse/merged_seurat_mouse.RData")
```

```{r subset-seuratobject-by-sampletags}
merged_filtered_seurat <- subset(merged_seurat, subset = Sample_Tag != 'NA' & Sample_Tag != 'Undetermined' & Sample_Tag != 'SampleTag01_hs' & Sample_Tag != 'Multiplet')

merged_filtered_seurat$nCount_RNA <- NULL
merged_filtered_seurat$nFeature_RNA <- NULL
```

```{r}
merged_filtered_seurat_meta <- merged_filtered_seurat@meta.data
```

```{r subset-metadata-to-get-the-different-conditions}
subset_control <- subset(merged_filtered_seurat_meta, Sample_Tag == "Control" | Sample_Tag == "Control_tagged")
subset_alpelisib <- subset(merged_filtered_seurat_meta, Sample_Tag == "Alpelisib")
subset_copanlisib <- subset(merged_filtered_seurat_meta, Sample_Tag == "Copanlisib")
```

```{r Control-tags, fig.cap="The figures are showing different quality metrices for the control samples."}
#cell count
subset_control %>% 
  	ggplot(aes(x=Xenograft, fill=Xenograft)) + 
  	geom_bar() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells from the untreated xenografts")+
    scale_fill_lancet()

# Extract identity and sample information from dataframe to determine the number of cells per sample_tag
n_cells_control<- table(subset_control$Sample_Tag)

# View table
kable(n_cells_control,
      col.names = c("Sample_Tag",
                    "nCells"),
      caption = "The table shows the number of cells which were untreated.")

#UMI count
subset_control %>% 
  	ggplot(aes(color=Xenograft, x=nUMI, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() + 
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("nUMi from the control xenografts")+
    scale_fill_lancet()

#Gene Count
subset_control %>% 
  	ggplot(aes(color=Xenograft, x=nGene, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("nGene from the control xenografts")+
    scale_fill_lancet()

#joint filtering effect
subset_control %>%
  	ggplot(aes(x=nUMI, y=nGene)) +
  	geom_point() +
	scale_colour_gradient(low = "gray90", high = "black") +
  	stat_smooth(method=lm) +
  	scale_x_log10() +
  	scale_y_log10() +
  	theme_classic() +
  	geom_vline(xintercept = 500) +
  	geom_hline(yintercept = 250) +
  	facet_wrap(~Sample_Tag)+
    scale_fill_lancet()

#Mitochondrial count
subset_control %>% 
  	ggplot(aes(color=Xenograft, x=percent.mt, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() +
  	geom_vline(xintercept = 2)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("Mitochondrial gene expression in [%] \n from the control xenografts")+
    scale_fill_lancet()
```

```{r Copanlisib-tag, fig.cap="The figures are showing different quality metrices for the copanlisib samples."}
#cell count
subset_copanlisib %>% 
  	ggplot(aes(x=Xenograft, fill=Xenograft)) + 
  	geom_bar() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells from the xenografts treated with Copanlisib")+
    scale_fill_lancet()

# Extract identity and sample information from dataframe to determine the number of cells per sample_tag
n_cells_copanlisib<- table(subset_copanlisib$Sample_Tag)

# View table
kable(n_cells_copanlisib,
      col.names = c("Sample_Tag",
                    "nCells"),
      caption = "The table shows the number of cells which were treated with Copanlisib.")

#UMI count
subset_copanlisib %>% 
  	ggplot(aes(color=Xenograft, x=nUMI, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("nUMI from the xenografts treated with Copanlisib")+
    scale_fill_lancet()

#Gene Count
subset_copanlisib %>% 
  	ggplot(aes(color=Xenograft, x=nGene, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("nGene from the xenografts treated with Copanlisib")+
    scale_fill_lancet()

#joint filtering effect
subset_copanlisib %>%
  	ggplot(aes(x=nUMI, y=nGene)) +
  	geom_point() +
	scale_colour_gradient(low = "gray90", high = "black") +
  	stat_smooth(method=lm) +
  	scale_x_log10() +
  	scale_y_log10() +
  	geom_vline(xintercept = 500) +
  	geom_hline(yintercept = 250) +
  	facet_wrap(~Sample_Tag)+
    scale_fill_lancet()

#Mitochondrial count
subset_copanlisib %>% 
  	ggplot(aes(color=Xenograft, x=percent.mt, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	geom_vline(xintercept = 2)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("Mitochondrial gene expression in [%] from \n the xenografts treated with Copanlisib")+
    scale_fill_lancet()
```

```{r Alpelisib-tag, fig.cap="The figures are showing different quality metrices for the alpelisib samples."}
#cell count
subset_alpelisib %>% 
  	ggplot(aes(x=Xenograft, fill=Xenograft)) + 
  	geom_bar() +
  	theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("NCells from the xenografts treated with Alpelisib")+
    scale_fill_lancet()

# Extract identity and sample information from dataframe to determine the number of cells per sample_tag
n_cells_alp<- table(subset_alpelisib$Sample_Tag)

# View table
kable(n_cells_alp,
      col.names = c("Sample_Tag",
                    "nCells"),
      caption = "The table shows the number of cells which were treated with Alpelisib.")

#UMI count
subset_alpelisib %>% 
  	ggplot(aes(color=Xenograft, x=nUMI, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
    scale_x_log10() +
  	ylab("Cell density") +
  	geom_vline(xintercept = 500)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("nUMI from the xenografts treated with Alpelisib")+
    scale_fill_lancet()

#Gene Count
subset_alpelisib %>% 
  	ggplot(aes(color=Xenograft, x=nGene, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) +
  	scale_x_log10() + 
  	geom_vline(xintercept = 300)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("nGene from the xenografts treated with Alpelisib")+
    scale_fill_lancet()

#joint filtering effect
subset_alpelisib %>%
  	ggplot(aes(x=nUMI, y=nGene)) +
  	geom_point() +
	  scale_colour_gradient(low = "gray90", high = "black") +
  	stat_smooth(method=lm) +
  	scale_x_log10() +
  	scale_y_log10() +
  	geom_vline(xintercept = 500) +
  	geom_hline(yintercept = 250) +
  	facet_wrap(~Sample_Tag)+
    scale_fill_lancet()

#Mitochondrial count
subset_alpelisib %>% 
  	ggplot(aes(color=Xenograft, x=percent.mt, fill=Xenograft)) + 
  	geom_density(alpha = 0.2) + 
  	scale_x_log10() + 
  	geom_vline(xintercept = 2)+
    theme(plot.title = element_text(hjust=0.5, face="bold")) +
  	ggtitle("Mitochondrial gene expression in [%] from \n the xenografts treated with Alpelisib")+
    scale_fill_lancet()
```

```{r}
merged_filtered_seurat_meta %>% 
    ggplot(aes(x=Xenograft, fill=nUMI)) + 
    geom_bar() +
    labs(x="Xenografts", y="Number of cells",
               title="Overview of the number of cells by xenografts and condition") +
    facet_grid(~Sample_Tag) +
    theme(axis.text.x = element_text(angle=45, vjust=1, hjust=1)) +
    scale_fill_lancet()
```

```{r set-threshold}
filtered_seurat <- subset(x = merged_filtered_seurat,
                                       subset= (nUMI >= 500) & 
                                      (nGene >= 250) & 
                                      (log10GenesPerUMI > 0.80) & 
                                      (percent.mt < 5))
```

```{r}
# Extract counts
counts <- GetAssayData(object = filtered_seurat, slot = "counts")

# Output a logical matrix specifying for each gene on whether or not there are more than zero counts per cell
nonzero <- counts > 0
```

```{r}
# Sums all TRUE values and returns TRUE if more than 10 TRUE values per gene
keep_genes <- Matrix::rowSums(nonzero) >= 10

# Only keeping those genes expressed in more than 10 cells
filtered_counts <- counts[keep_genes, ]
```

```{r}
filtered_seurat <- CreateSeuratObject(filtered_counts, meta.data = filtered_seurat@meta.data)
```

```{r}
save(filtered_seurat, file="E://CCCC/PI3K/data/SeuratObjects/filtered/Mouse/filtered_seurat.RData")
```